### ISSUE TITLE
transfer driver/example to driver/examples

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#10]
please transfer dir into examples with name - "DataLogging"

and add some code to main to store data of all sensors in tsv-format just like in old project.

**Comment by iluxa** [comment]
PR created https://github.com/panda-official/TimeSwipe/pull/18:
- moved example to driver/examples/DataLogging
- moved sleep 100ms from user code to the driver code
- added example option --dump to dump to stdout all sensors instead of firsts

**Comment by IngoKaiser** [comment]
Move sleep back into user loop. Or lets discuss another way - just the way we talked about it on channel.

**Comment by iluxa** [comment]
Moved sleep back to the user, new PR:
https://github.com/panda-official/TimeSwipe/pull/19

**Comment by IngoKaiser** [comment]
hey @iluxa beside changes I am missing integration of properly saving data in file ;) Please Check that and do integration.

**Comment by iluxa** [comment]
current version let user put `--dump` flag and redirect standard output to the file. I thinks it is a good way to save data to the file, original version has filename hardcoded, should we add new option like 
`--output` for user to save into the file or keep this implementation with redirecting standard output?

**Comment by IngoKaiser** [comment]
@iluxa thats a very good idea

**Comment by iluxa** [comment]
@k41532 what exactly good - leave it as it is or add `--output` flag?

**Comment by IngoKaiser** [comment]
😁I mean your idea. —output flag

**Comment by IngoKaiser** [comment]
Let’s also switch config behavior. 

Let’s put chosen input type as selection in there not as option to be chosen by additional flag as flag as of now. 

Let’s work with flag —config therefore. When none is set we use NORM as default with 0 for each offset and 1 for all gains and transmissions. 

@iluxa 
What do you think?

**Comment by iluxa** [comment]
yes, then command line will be:
```
./main [--config <filename>] [--input <input_type>] [--output <filename>]
```
`config.json` is default for `--config` option
first input type from config file is default for `--input` option

**Comment by IngoKaiser** [comment]
perfect

**Comment by iluxa** [comment]
added PR https://github.com/panda-official/TimeSwipe/pull/21
