### ISSUE TITLE
build incompatible new firmware by default with no mention in READEM

### ISSUE THREAD

**Issue by mjleehh** [panda-official/TimeSwipe#106]
#In the firmware README there is no mention of:
- the two board types
- the fact that the new board firmware is not binary compatible to the old board
- the DMS CMake option that is enabled by default in newer firmeware builds
thus anyone trying to flash older types of boards will be confronted with a firmware that can be flashed but simply does not work.

See eb9b261641d28c39735fea1c2cfa29eb7088ff08

**Comment by begodev** [comment]
Fixed in https://github.com/dmitigr/TimeSwipe/tree/cmake-stuff-refactoring
