### ISSUE TITLE
EEPROM i2c

### ISSUE THREAD

**Issue by mjleehh** [panda-official/TimeSwipe#107]
file driver/src/timeswipe_eeprom.cpp:15 assumes the i2c device to be located at "/sys/class/i2c-adapter/i2c-0/new_device"

On Raspberry OS this is not always the case: the corresponding element can just as well be located at ""/sys/class/i2c-adapter/i2c-1/new_device" for example.

**Comment by begodev** [comment]
The issue is related to the issue #90
