### ISSUE TITLE
building driver on raspberry OS

### ISSUE THREAD

**Issue by mjleehh** [panda-official/TimeSwipe#108]
The information in driver/README.md is inaccurate:
The driver/src/CMakeLists.txt is set up for cross compilation. It always searches for a toolchain file and then defaults to cross compilation on Arch Linux.

**Comment by begodev** [comment]
checked with https://github.com/dmitigr/TimeSwipe/tree/cmake-stuff-refactoring

**Comment by dmitigr** [comment]
This is resolved now.
