### ISSUE TITLE
Utilisation of new board features

### ISSUE THREAD

**Issue by thomaseichhorn** [panda-official/TimeSwipe#109]
The new TimeSwipe board has new features like setting mode, gain and IEPE for each channel (c.f. docs/CommunicationProtocol.md) and setting an output voltage.

For ease of usage, this should be accessible directly from the driver without having to go through SPI commands; ideally within the datalogging example.

**Comment by begodev** [comment]
[+] Additions to the driver's API to set mode, gain and IEPE for each channel. Tested @10.0.0.38
[+] Added "CONFIG_SCRIPT" option in the  config.json of the DataLogging example to allow the board configuration at the start via the single js< command

**Comment by pmalessa** [comment]
is added, can be closed
