### ISSUE TITLE
LED visualisation in current FW master

### ISSUE THREAD

**Issue by thomaseichhorn** [panda-official/TimeSwipe#116]
In the current firmware master branch, the visualisation of input signal levels via the 4 status LEDs is no longer active. This was the case for firmware versions v0.0.16 and previous.

Is there a reason this has been disabled? Can it be readded?

**Comment by begodev** [comment]
Should be there. I'll check

**Comment by begodev** [comment]
Looks like the LED driver was broken during latest total project rearrangement.
Should work now

**Comment by pmalessa** [comment]
Does work now :)
