### ISSUE TITLE
Native driver build on arm

### ISSUE THREAD

**Issue by thomaseichhorn** [panda-official/TimeSwipe#118]
When building the driver of the current master natively on an arm device, the cross-compiling flag `CMAKE_CROSSCOMPILING` is not recognized (line 466), so CMake doesn't link the atomic library, thus failing the build.
Commenting out the check works, build is successful.
I'm not sure what the best way to fix this is...

**Comment by dmitigr** [comment]
Fixed in 57fed6390bb6da4b0367309220cab597b7a261fa. Thanks!
