### ISSUE TITLE
Pi undervoltage interferes with measurement frequencies

### ISSUE THREAD

**Issue by ghost** [panda-official/TimeSwipe#119]
We noticed that some devices when using the ```datlog``` sample program were sampling at lower than expected frequencies. 
When 48KHz was specified, we were only getting ~24KHz. 
Checking dmesg we noticed that the Pi kernel was issuing undervoltage warnings like:

```
Under-voltage detected! (0x00050005)
rpi_firmware_get_throttled: 1 callbacks suppressed
```
When the power regulator was adjusted the issue seemed to go away. 

Should a warning be raised by the driver if the device is not performing correctly, as in this case?

**Comment by pmalessa** [comment]
moved to gitlab
