### ISSUE TITLE
Create modern Readme 

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#12]
![TimeSwipe_3_no stroke](https://user-images.githubusercontent.com/24693067/68896218-4a508300-072b-11ea-9a03-4ddd721911f0.png)

Example attached.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/24693067/68896323-7f5cd580-072b-11ea-9c8d-0cfe36e8b2a0.png">

Who wants to do it?

**Comment by IngoKaiser** [comment]
![PANDA Timeswipe (all black)](https://user-images.githubusercontent.com/24693067/68896727-66a0ef80-072c-11ea-8cf5-e15285eff074.png)

With title like this ... I just think without logo and PANDA :)

**Comment by IngoKaiser** [comment]
Perhaps we can integrate Subheaders like:

**Install**
-> link to readme for building drivers for several os

**Documentation**
-> link to firmware doc
-> link to communication protocol doc
-> link to driver doc

**RPi Examples**
-> link to Rpi examples

**Customizing Firmware**
-> link to building and flashing firmware
-> link to firmware examples

**License**

Other ideas for Main Readme really appreciated. Also about other readme files -> have them in according repo or together in docs dir? 

Please give me feedback on that @iluxa @begodev

**Comment by pmalessa** [comment]
Driver Documentation Generation from Doxygen:
example: https://phoggy.github.io/TimeSwipe/annotated.html
have a look at my fork of TimeSwipe: https://github.com/PhoGGy/TimeSwipe/blob/doxygen/.github/workflows/main.yml
This is a working Github Action to build the Doxygen Documentation from every push and upload it to the gh-pages branch, from where it gets automatically deployed to GitHub.io
