### ISSUE TITLE
Looks like we are loosing data

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#15]
<img width="1265" alt="Bildschirmfoto 2019-11-12 um 16 26 12" src="https://user-images.githubusercontent.com/24693067/68994651-9dd6e400-0885-11ea-9dd7-d84e89481097.png">

This is a triangle signal on the data. It looks like I was to slow with lib. We need to get 48k fps. Do we get that? Whats the cpu load like?

Please do some testing.

**Comment by iluxa** [comment]
At first we can add data losing check for intto the library
criteria might be if data received later than 500ms after previous data received

How is it possible to measure fps? Is it expecting to receive 48k records per second?

**Comment by iluxa** [comment]
Going to resolve https://github.com/panda-official/TimeSwipe/issues/11 before continue testing, it seems data are losing because of real sleep is different from intended

**Comment by iluxa** [comment]
After some testing, I found that printing data takes a lot of time and causes losing data.
Even not printing but formatting float pointer numbers.
The issue can be solved by multithread application with lockfree queue.
I get it working without losing data by using [boost::lockfree:spsc_queue](https://www.boost.org/doc/libs/1_66_0/doc/html/boost/lockfree/spsc_queue.html)
We can generate errors counter from the driver side to the user application.

**Comment by iluxa** [comment]
PR: https://github.com/panda-official/TimeSwipe/pull/23
driver reads from sensors to its own buffer in own thread
application reads data from driver buffer
application also reads error counter - how many entries have been lost in the buffer
add debian 32bit packed build

**Comment by iluxa** [comment]
checked on raspbian - getting 48K fps

**Comment by IngoKaiser** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/24693067/69613409-d0c16a80-1031-11ea-89e7-14b30897a684.png">
