### ISSUE TITLE
Optimize Board Interface

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#16]
- [x] User should be able to request settings like `js>["a","b","c"]\n`

- [x] User should get all settings with `js>\n` (just like he can for je)

- [x] Add js and je explanation to docs

**Comment by i5abell** [comment]
@begodev json object is not found.. I tested it with the rPIspi terminal. It is maybe not the latest version, but it has worked with the newer firmware versions.

![Bildschirmfoto vom 2019-11-28 12-33-35](https://user-images.githubusercontent.com/50866829/69803363-479a6700-11dc-11ea-8f32-d85d26f37bfe.png)
