### ISSUE TITLE
Update Driver API

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#22]
Timeswipe

- bool init => runs single Set* for according Board… SetInput: - Define defaults; tbd! Integration when EEPROM is implemented

- bool start(std::function<void(std::vector<Record>)> cb) => error and message (vector of Records) as input for callback!

- response setSecondary => I thought about that. Instead of setting DMS, IEPE, NORM... we have severals boards (two atm - one especially for DMS and one especially for IEPE - both have option to measure normalized signal (NORM) as well - we could choose this with this option - so primary would be default.

- response setBridge(int bridge)

… additional Set*

- bool onButton(std::function<void(bool)> cb)

- bool onError(std::function<void(bool)> cb)

- getEEPROM() => tbd: define result type!

- SPI => should be initialized at init() => other communications should build on that
    - bool send(msg)
    - receive() => tbd: define result type!

response could be always (error + msg)? Let's spar on this and get it integrated fast.

**Definition of Done**
- [ ] code for mentioned task is complete. examples & documentations are complete.

- [ ] build chains are tested

- [ ] corresponding branch is closed

- [ ] merging is done

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/pull/28
onError and onButton are implemented

**Comment by iluxa** [comment]
added SetSecondary, Init, SetSettngs, GetSettings

**Comment by IngoKaiser** [comment]
@iluxa We will get a third node - therefore please change setSecondary to setMode with new inputs (0=IEPE/DMS according to board - can be seen in eeprom, 1=NORM, 2=DIGITAL - we will come to that later)

Each mode will result in a different SPI Message.
Please ping me for message content when this is ready.

Please delete setbridge - we will do that and some others with setsettings,

Also no need for Init - was bad idea 😇

To keep it flexible I also just thought about replacing onButton with onEvent to catch all possible events from arm - the. User should be able to if on any specific event in callback, right? @iluxa

**Comment by iluxa** [comment]
@IngoKaiser Can you please explain
setMode - what this function should do? And what is the format?

> Each mode will result in a different SPI Message.

Which SPI messages?

**Comment by iluxa** [comment]
Pushed current changes to [branch](https://github.com/panda-official/TimeSwipe/tree/issue_22)
Waiting for Mode implementation and calibration EEPROM atom on firmware side in [issue 69](https://github.com/panda-official/TimeSwipe/issues/69)

**Comment by begodev** [comment]
"Mode" AP is added...

**Comment by IngoKaiser** [comment]
@iluxa could you please test setting mode?

**Comment by iluxa** [comment]
Merged issue_22 branch into [NewMenu](https://github.com/panda-official/TimeSwipe/tree/NewMenu) branch. Continue development there.
