### ISSUE TITLE
EEPROM: Delete external Interfaces  

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#3]
The EEPROM may only be written to by the I2C connections of the SAM. All interfaces to external connectors like 8pin Connector or HAT plug have to be removed in respect to writing to the EEPROM.

**Comment by begodev** [comment]
Interface was removed

**Comment by IngoKaiser** [comment]
@LeilaPiri could you please clarify reopening?

**Comment by LeilaPiri** [comment]
> @LeilaPiri could you please clarify reopening?
issue should be reviewed before being closed.

**Comment by IngoKaiser** [comment]
ok thought 👍 was review :)

@begodev could you please tell commit of removing interface?

**Comment by i5abell** [comment]
@begodev I have seen that you have removed the I2C slave for the 8 pin connector and its connection to the EEPROM buffer in the main.cpp. If I see it right, the HAT EEPROM code block is still the same. Just the headline has changed from "R/W EEPROM data from extension plugs" to "Read-only EEPROM data from extension plugs"? Is it still possible for the rPi to write EEPROM data via HAT I2C or have you disabled it elsewhere?

**Comment by begodev** [comment]
@k41532: the commit was:

commit 7ae428607b2859ed5fef26b0b6a8e432fefabe47
Author: vnk <vnk@VNKpc.ru>
Date:   Mon Nov 11 16:57:01 2019 +0300

**Comment by begodev** [comment]
@i5abell 

> Is it still possible for the rPi to write EEPROM data via HAT I2C or have you disabled it elsewhere?

No, it is impossible since the writing code has been removed also from CSamI2CeepromMaster & CSamI2Cmem. They are both read-only now

**Comment by IngoKaiser** [comment]
ok, am I right that we 
- only have write access for HAT EEPROM on SAM,
- have I2C available on 8pin and
- have SPI available on 8pin?

**Comment by begodev** [comment]
from the current software part (at the master) we have read only access to HAT EEPROM from rPI,
write access on SAM (to fill the data buffer from the external chip)

And no any software interfaces for 8pin (I2C was removed: 2 lines of code are deleted)
