### ISSUE TITLE
Create non-volatile  structured storage based on HAT ID EEPROM FORMAT SPECIFICATION and ATOM structure convention

### ISSUE THREAD

**Issue by begodev** [panda-official/TimeSwipe#30]
1) The data should be stored in the non-volatile memory according to the ATOM abstraction and format
(https://github.com/raspberrypi/hats/blob/master/eeprom-format.md)

2) An interface should be implemented for storing / retrieving arbitrary data objects based on the type of object and its unique name or identifier

**Comment by IngoKaiser** [comment]
@begodev please give short notice about current state and code snippet on storing/reading data according to atom structure. 

@iluxa could you please confirm testing reading eeprom from pi?

**Comment by begodev** [comment]
Hello.
CHatsMemMan class in the HATS_EEPROM branch ( /src/HATS EEPROM, HatsMemMan.h, HatsMemMan.cpp) provides very basic functionality for retreiving/storing atoms from the binary blob.

Here is a snippet:

<pre><code>
#include "HatsMemMan.h"

//First of all a binary image has to be loaded in a FIFO buffer, for example:
 
auto pEEPROM_MemBuf=std::make_shared<CFIFO>(); //create a buffer
//add some binary image there (or load)
//.......................................................

//Then CHatsMemMan can be attached to the bufer:
CHatsMemMan HatMan(pEEPROM_MemBuf);

//The image has to be verified before use: Verify() methode will check the image consistency and CRCs of the atoms
CHatsMemMan::op_result res;
res=HatMan.Verify();

//The number of atoms can be obtained as following (optional)
unsigned int nAtoms=HatMan.GetAtomsCount();

//Then obligatory atoms can be obtained:
CHatAtomVendorInfo vi;
CHatAtomGPIOmap gpio;

res=HatMan.Load(vi);
res=HatMan.Load(gpio);
 
</code></pre>

**Comment by iluxa** [comment]
Here is a working application which read eeprom from device file and parses structures using API on timeswipeOS RPi:

```
#include "HatsMemMan.h"
#include <string>
#include <string.h>
#include <fstream>
#include <iostream>
#include <streambuf>

// before run:
// modprobe i2c_dev
// modprobe at24
int main() {
    const char* i2c_file = "/sys/class/i2c-adapter/i2c-0/0-0050/eeprom";
    std::ifstream t(i2c_file);
    if (!t.is_open()) {
        //echo "24c32 0x50" > /sys/class/i2c-adapter/i2c-0/new_device
        std::ofstream ofs("/sys/class/i2c-adapter/i2c-0/new_device");
        if (!ofs.is_open()) {
            std::cerr << "Can not access i2c subsystem. Check drivers are properly loaded" << std::endl;
            return -1;
        }
        const char* buf = "24c32 0x50\n";
        ofs.write(buf, strlen(buf));
        ofs.close();
        if (!ofs) {
            std::cerr << "Create i2c failed. Check permissions" << std::endl;
            return -1;
        }
        t.open (i2c_file, std::ifstream::in);
        if (!t.is_open()) {
            std::cerr << "Can not access i2c subsystem. Check drivers are properly loaded" << std::endl;
            return -1;
        }
    }
    std::string str((std::istreambuf_iterator<char>(t)),
                 std::istreambuf_iterator<char>());
    if (str.length() > 127) str.resize(127);
    auto buf = std::make_shared<CFIFO>();
    *buf += str;
    CHatsMemMan HatMan(buf);
    
    //The image has to be verified before use: Verify() methode will check the image consistency and CRCs of the atoms
    CHatsMemMan::op_result res;
    res=HatMan.Verify();
    
    //The number of atoms can be obtained as following (optional)
    unsigned int nAtoms=HatMan.GetAtomsCount();
    
    //Then obligatory atoms can be obtained:
    CHatAtomVendorInfo vi;
    CHatAtomGPIOmap gpio;
    
    res=HatMan.Load(vi);
    res=HatMan.Load(gpio);

    printf("uuid: %x-%x-%x-%x\n", vi.m_uuid[0], vi.m_uuid[1], vi.m_uuid[2], vi.m_uuid[3]);
    printf("pid: 0x%x\n", vi.m_PID);
    printf("vstr: %s\n", vi.m_vstr.c_str());
    printf("pstr: %s\n", vi.m_pstr.c_str());
    printf("GPIO:\n");
    for (int i = 0; i < 28; i++) {
        const auto& g = gpio.m_GPIO[i];
        printf("%d: func_sel: %u reserved: %u pulltype: %u is_used: %u\n",i+2, g.func_sel, g.reserved, g.pulltype, g.is_used);
    }    
}

```

The output is:
```
# ./eeprom_test 
uuid: 0-0-0-0
pid: 0x0
vstr: PANDA
pstr: TimeSwipe
GPIO:
...
```

It seems to be working correct so far
