### ISSUE TITLE
Testing sporadic communication errors returning by a driver function

### ISSUE THREAD

**Issue by begodev** [panda-official/TimeSwipe#31]
@gilyav has reported about sporadic communication errors returning by spi.receive method. This should be tested.

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by begodev** [comment]
spi_test is working more than hour on pi.panda.technology (Port 24) Board rev. 2.2 without any errors...

**Comment by IngoKaiser** [comment]
@iluxa do errors still occur?

**Comment by iluxa** [comment]
@k41532 just tested 3 times on 0.tcp.eu.ngrok.io:10274
error appeared after 12, 2, 3 seconds

**Comment by begodev** [comment]
The problem that some symbols in the message are sometimes missing.
This came from several reasons:
1) SPI's FIFO bufer has short length.
2) the interrupt routine seems too slow for current speed - should be optimized.
3) communication speed is too high.

**Comment by IngoKaiser** [comment]
@iluxa plesse confirm errors are not showing up any more?

**Comment by iluxa** [comment]
Last time I tested there were errors (before merge)
Where can I test it now?

**Comment by IngoKaiser** [comment]
Please ping @begodev therefore and give feedback when tested.

**Comment by iluxa** [comment]
tested on RPi with timeswipeOS
still getting error `protocol error: !obj_not_found!`

**Comment by begodev** [comment]
I've built test_spi from the actual driver sources (with reduced speed=50.000Hz). 
It gives no error so far: 10.0.0.12:/root/vnk/test_spi

**Comment by iluxa** [comment]
tested test_spi built on current master on Raspbian 32bit and timeswipeOS 64bit
both works without errors for a long time (>10 mins)
