### ISSUE TITLE
Do not Block user in Start call

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#33]
Start should create main loop and return immediately

**Comment by iluxa** [comment]
pushed changes in commit https://github.com/panda-official/TimeSwipe/commit/e5f416b2cf4d0c998606725ebab5f4f4dfc9f74e

**Comment by iluxa** [comment]
added delay to reduce cpu load:
https://github.com/panda-official/TimeSwipe/commit/f7bfdb210bd7f57e4b045f164cb5bc969165f305

**Comment by IngoKaiser** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/24693067/70893925-55c5f100-1fec-11ea-8d33-1eac277d8284.png">

Getting acceptable cpu workload.
