### ISSUE TITLE
Implement ci/cd for the driver

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#34]
on git tag created new versions should be generated:
driver packages (for debian and arch)
python and nodejs modules

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by iluxa** [comment]
Added configuration to githab workflow for [TimeSwipe](https://github.com/panda-official/TimeSwipe) repo([Actions](https://github.com/panda-official/TimeSwipe/actions)) and [TimeSwipe.js](https://github.com/panda-official/TimeSwipe.js) repo([Actions](https://github.com/panda-official/TimeSwipe.js/actions))

On each push to the master branch CI tries to build all packages - the result is displayed on the badge: 
![](https://github.com/panda-official/TimeSwipe/workflows/Workflow/badge.svg)

Information how to make new release added to [Readme.md](https://github.com/panda-official/TimeSwipe/blob/master/driver/Readme.md)

**Comment by IngoKaiser** [comment]
@iluxa would you also update Timeswipe.py and add Actions?

**Comment by iluxa** [comment]
Yes, will update today
