### ISSUE TITLE
Make gain and transmission floats

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#35]
Since we have calculated gains and sensor transmissions with decimals, let’s make them float. 
**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by IngoKaiser** [comment]
@iluxa also according to that - should we replace division by multiplication for performance reasons?

**Comment by iluxa** [comment]
yes, replacing division with multiplication should increase the performance

**Comment by iluxa** [comment]
PR https://github.com/panda-official/TimeSwipe/pull/66
changed gains and transmissions to float, replaced division to multiplication on sensors read
performance looks same, maybe because of compiler optimizations

**Comment by begodev** [comment]
Would it be possible to send already pre-calculated (gain x transmission)=mfactor instead of sending them to the convertChunkToRecord separately?
I think it could remove one FMUL instruction

**Comment by iluxa** [comment]
replaced gain*transmission with mfactor on https://github.com/panda-official/TimeSwipe/commit/1f1dd9ce2b063a58a8346c1f8353d090b82437d7
