### ISSUE TITLE
Change SetBridge to SetSecondary

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#39]
On current board (IEPE) we misused SetBridge for changing between IEPE or Normsignal. 
Therefore we added "SetSecondary" in driver:
0 = IEPE
1 = Normsignal

Please also change this in Firmware to avoid confusion.

We will have SetBridge on our other Board (DMS), therefore we should have this setting, but interface in Firmware will change in next step.

@iluxa @begodev please check, that driver and firmware are working on that change properly.

**Comment by begodev** [comment]
"SetSecondary" has been added to the firmware in the "issue31_39" branch

**Comment by IngoKaiser** [comment]
@iluxa please adjust SetSecondary in driver accordingly.
