### ISSUE TITLE
Remote Test EEPROM

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#4]
1. The reading of data from the external EEPROM has to be tested.
2. The writing of data to the external EEPROM has to be tested.
3. The mirroring of the data in the external EEPROM to the HAT EEPROM and reading out the data    
     via rPi has to be tested.

Feedback has to be implemented. For writing to the EEPROM the feedback should be "success" or an error message. For reading the data in the EEPROM there also has to be feedback implemented, if the data could be read correctly.

**Comment by LeilaPiri** [comment]
OpenOCD installation under the current distributive of ArchLinux is not so trivial as for Raspbian.
Configure script just skips the --enable-bcm2835gpio option for some reason(doesn't find *ARM keyword in a $host_cpu ? ), so manual patching was required to make a correct build...

**Comment by acolomb** [comment]
If you find a solution to this, please consider contributing it to the upstream OpenOCD packaging in Arch.  There is already an up-to-date version of openocd available in the package archives, but it's missing the bmc2835gpio interface code as well, unfortunately.  Would be a breeze to just have it available via pacman...

**Comment by begodev** [comment]
/dev/i2c-X doesn't appear after loading i2c_dev module by modprobe under a new system.
Is it planned to use HAT's eepromutils for programming the EEPROM or I2C will be complitely hidden?

**Comment by IngoKaiser** [comment]
@begodev I thought of having utils in repo itself, but only having read function implemented in firmware. Write function needs to be added to calibration firmware. Read is also available on Pi for reading HAT EEPROM (mirrored smart EEPROM of SAM).

**Comment by IngoKaiser** [comment]
We have a pi online with new Board (connected EEPROM with pullups).

Type `ssh ssh://root@0.tcp.eu.ngrok.io:10089` (root:panda)

I will replace address within next days

@begodev could you test EEPROM utils with that next?

**Comment by begodev** [comment]
Ok. Is there also an I2C-0 dev activated? I'll look there...

**Comment by IngoKaiser** [comment]
Should be available.

**Comment by begodev** [comment]
So external HAT interface seems to be working: I see the board via i2c-0 under the Linux and can readout the data. But is the external EEPROM chip is already connected with pullups? Right now its still "arbitration loss"
May I also change a root password?

**Comment by IngoKaiser** [comment]
External EEPROM should also have pull-ups, but they are added manually. There might be a connection issue. 🤔

You can change pw - but why?

**Comment by begodev** [comment]
> External EEPROM should also have pull-ups, but they are added manually. There might be a >connection issue. 🤔

Oh, sorry this time it was address mismatch...

>You can change pw - but why?

I just thought if some anonymous outside the team reads this and may decide to login,  some armateur young hacker )

**Comment by begodev** [comment]
Oh, sorry this time it was address mismatch...

Now I can make some communication with a chip at address 0xA0, at least I see how the bus is going through the corresponding states. It seems hardware is ok at first sight. I'm continuing testing...

**Comment by IngoKaiser** [comment]
👍
Did you have a look at eeprom specs?

https://github.com/raspberrypi/hats/blob/master/eeprom-format.md

**Comment by begodev** [comment]
Yes, previously I used eeprom utils to create the eeprom image automatically

**Comment by IngoKaiser** [comment]
@begodev so you have access on both EEPROM? 

from SAM you can access EEPROM (r/w) and HAT EEPROM (r/w)
from RPi you can access HAT EEPROM (r)

if that's right, close issue and open new one for clarifying r/w utils and content (teaser: should follow this: https://github.com/raspberrypi/hats/blob/master/eeprom-format.md
