### ISSUE TITLE
add sample rate setting

### ISSUE THREAD

**Issue by mkh-welsch** [panda-official/TimeSwipe#45]
the 5-pol analog filter in the hardware is optimized for the 48kHz samples per second. anyways, if the user wants a lower sample rate, the original signal has to be digitally filtered before downsampling the values. this should be implemented in the driver.

this here seems to be a good starting point.
https://github.com/terrygta/SignalResampler

if we resample block-wise, there are artifacts at the start and the beginning due to the math behind resampling and filters, so it needs paddings from original data to overcome this problem. Here you take larger blocks (adding pads), apply resampling, and then cut the additional pad information in the result.

**Comment by IngoKaiser** [comment]
@iluxa we should add new method therefore. with resulting fps in `Start` callback then - default is 48k.

**Comment by iluxa** [comment]
Initial implementation is on the branch [issue_45](https://github.com/panda-official/TimeSwipe/tree/issue_45)
implementation is based on https://github.com/terrygta/SignalResampler
with padding

tested on RPi without triangular signal - CPU CORE usage is incremented about 10-15%
Future activities: test with triangular signal; memory copiyng optimizations

**Comment by iluxa** [comment]
Tests with triangular signal:

![Without resample](https://user-images.githubusercontent.com/1526529/74832603-ba713500-5328-11ea-8a22-44b2bfa72547.png)
![with 24K resample](https://user-images.githubusercontent.com/1526529/74832621-c65cf700-5328-11ea-97c0-dfa54ac23ae8.png)
![with 5K resample](https://user-images.githubusercontent.com/1526529/74832630-cd840500-5328-11ea-8b0a-2a61c9fd2b49.png)

**Comment by iluxa** [comment]
First without resample
Second with 24K resample
Third with 5K resample

**Comment by IngoKaiser** [comment]
@mkh-welsch expected result?

**Comment by mkh-welsch** [comment]
<img width="490" alt="image" src="https://user-images.githubusercontent.com/24566838/75089863-67cc8e80-555d-11ea-9581-854100257488.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/24566838/75089865-6dc26f80-555d-11ea-89e7-6f3e2cb08a2b.png">
looks like the instability, we try to avoid with the padding. try to increase the padding size.

**Comment by mkh-welsch** [comment]
@iluxa : maybe dynamically increase the padding size with lower resample rate.

**Comment by mkh-welsch** [comment]
effect of not using paddings during resampling.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/24566838/75091032-525d6180-5569-11ea-9605-2b40c90e45a6.png">

top: original without resample
middle: resampled without using padding logic
bottom: resampled with padding.

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/commit/faec13067c993560de034296f4a68270429e02d3
dynamic padding size is implemented

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/commit/80c31d1f8a7bbbb37539708f7a9c8c471e129264
constant size slices

**Comment by iluxa** [comment]
PR for merge
https://github.com/panda-official/TimeSwipe/pull/62
