### ISSUE TITLE
timeswipe for python or node-red on windows

### ISSUE THREAD

**Issue by mhechthz** [panda-official/TimeSwipe#53]
Hi,

I'm not sure wether this is the right channel for communication but I didn't find a better place.

I wanted to install the timeswipe access for a windows system on an up-to-date 64-bit python or the latest node.js/node-red. Both failed (pip install timeswipe or npm install timeswipe).

Did anyone manage to install one of the mentioned libraries on a windows system?

**Comment by IngoKaiser** [comment]
Hey @mhechthz,
Since this module is for accessing Timeswipe HAT for Raspberry Pi with GPIO. Prebuilt binaries are prepared for ARM 32bit and ARM 64 OS. So it’s not possible to run on windows.
