### ISSUE TITLE
Read EEPROM from the driver and apply related settings

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#55]
**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by IngoKaiser** [comment]
when the calibration station is ready, an additional calibration atom is created. From this, the appropriate conversion can be taken according to the pid and settings for gain and supply voltage.

so setGain will be dine automatically - user will not have access later. 
so first step would be to read, second to set according setting

**Comment by iluxa** [comment]
Read EEPROM implementation: https://github.com/panda-official/TimeSwipe/pull/58
Further instructions needed how to convert EEPROM data to Settings

**Comment by iluxa** [comment]
Merged https://github.com/panda-official/TimeSwipe/pull/58 - it also fixes driver build

**Comment by begodev** [comment]
bool TimeSwipeEEPROM::Read(std::string& error) is working, but would be good to have the atoms as function's output.

**Comment by iluxa** [comment]
>bool TimeSwipeEEPROM::Read(std::string& error) is working, but would be good to have the atoms as function's output.

I don't think the driver (timeswipe.cpp) should think in terms of `CHatAtom*` structures, the idea is to convert information from atoms to settings like gains

@IngoKaiser do we need to set according settings from EEPROM to the driver in the scope of this issue?

**Comment by IngoKaiser** [comment]
@iluxa no, lets create new issue with read from EEPROM and set settings for backlog. 

> bool TimeSwipeEEPROM::Read(std::string& error) is working, but would be good to have the atoms as function's output.

@begodev that does not need to be accessible for user. So I guess we will just use it from read to be flexible and reduce workload.

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/issues/69
