### ISSUE TITLE
DataLogging abnormal termination

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#56]
Message on exit
```
terminate called without an active exception
Aborted
```

it seems thread not terminated at exit

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/pull/60 Join thread at `Stop`, call stop in distructor fixes the issue

**Comment by begodev** [comment]
Driver and Data Logging example were built on Debian-10. The application is finished normally
