### ISSUE TITLE
Artifacts at the data begin

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#61]
It happens unrelated to resampling or burst
![Screenshot from 2020-02-27 14-39-17](https://user-images.githubusercontent.com/1526529/75441835-6c36e400-596f-11ea-800f-c81434d0aeb9.png)
![Screenshot from 2020-02-27 14-42-03](https://user-images.githubusercontent.com/1526529/75441841-6f31d480-596f-11ea-90f9-f4a438be4291.png)

**Definition of Done**

- [ ]   code for mentioned task is complete. examples & documentations are complete.

- [ ]   build chains are tested

- [ ]   corresponding branch is closed

- [ ]   merging is done

**Comment by iluxa** [comment]
Before the fix driver skip only first bundle of data read (usually 64 values)
According to the tests about the first 900 values makes an "artifact"
It is not specified how much data to skip, it seems that depends on the hardware resampler
it must be specified and put to constant `clearFirst`

PR: https://github.com/panda-official/TimeSwipe/pull/67
`clearFirst` set there to 1000

**Comment by IngoKaiser** [comment]
this should be a hardware issue

@thomaseichhorn - could you provide access to one of the new boards (0.4.2) for @iluxa to recheck issue there? then we can just discard pr

**Comment by thomaseichhorn** [comment]
I can check this here with one of the new boards and try some values of clearfirst... I'll report back asap.

**Comment by thomaseichhorn** [comment]
As it turns out, this is a hardware issue which is fixed from board versions 0.4.2 onwards. Attached is the resulting plot when using the previous default (aka no clearfirst):
![default](https://user-images.githubusercontent.com/7010830/77431040-6e5c5900-6ddc-11ea-93b1-6324befe9572.png)

**Comment by IngoKaiser** [comment]
@iluxa would you please discard pr #67 - thanks for investigation!
