### ISSUE TITLE
JSON parser sometimes fails in Data Logging example

### ISSUE THREAD

**Issue by begodev** [panda-official/TimeSwipe#63]
![image](https://user-images.githubusercontent.com/52575842/75687536-ff915180-5cae-11ea-8aa3-564c8f620266.png)

Definition of Done

- [x]   code for mentioned task is complete. examples & documentations are complete.

- [x]   build chains are tested

- [x]   corresponding branch is closed

- [x]   merging is done

**Comment by begodev** [comment]
Driver & Data Logging Example were built on Debian-10...

**Comment by iluxa** [comment]
It seems to be issue with encoding
@begodev can you attach corresponding json file please?

**Comment by begodev** [comment]
[config.json.zip](https://github.com/panda-official/TimeSwipe/files/4280886/config.json.zip)

the file is taken from 10.0.0.12/root/vnk

**Comment by iluxa** [comment]
Attached file doesn't produce any errors
Maybe this file has been saved in Windows in some encoding like UTF-16, then copied to RPi
It seems encoding detection needed and check if a file exists.

**Comment by iluxa** [comment]
Added open file and parse exception handlers: https://github.com/panda-official/TimeSwipe/pull/68

I couldn't reproduce errors from the screenshot: tried run example on RPi several times without any errors.

@begodev Can you please test again and ping me when you get this error again

**Comment by begodev** [comment]
Ok, with try/catch blocks added it seems the software is working properly.
