### ISSUE TITLE
Restructure driver output

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#70]
@iluxa as we just have talked about, please make suggestion for data structure for column (signal)-wise data output.  

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by iluxa** [comment]
instead of Record data structure used in TimeSwipe atm:
```
struct Record
{
    std::array<float, 4> Sensors{0};
};
```
we can implement class contains bulk sensor data with random access to sensor and data each element:
```
class SensorsData {
    static constexpr size_t SENSORS = 4;
    std::array<std::vector<float>, SENSORS> data;
public:
    const std::vector<float> operator[](size_t num) const;
    size_t SensorsSize() const;
    size_t DataSize() const;    
};
```
so, `SensorsData[i]` is vector of data of sensor `i`

**Comment by IngoKaiser** [comment]
I think that's fine @iluxa

**Comment by iluxa** [comment]
https://github.com/panda-official/TimeSwipe/pull/71
