### ISSUE TITLE
CalFW: Copy current Production firmware and simplify

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#74]
Components to remove:
 

- [x] Visualization of Measurement Values
- [x] Menu Control via Button incl. Visualization on LEDs
- [x]  Blinking after Startup
- [x]  Setting a marker
- [x]  Differentiation between Short/Long/Double Click, only single short click needed

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by pmalessa** [comment]
The goal is to create a separate firmware based on the current production firmware. This calibration firmware will be used to test and calibrate the Timeswipe board after production. The mentioned components are not necessary for the calibration firmware.
Please create a branch for that

**Comment by pmalessa** [comment]
Issue 75..82 are for the calibration firmware

**Comment by begodev** [comment]
Is it possible to combine #81 & #77 also with master? Because temperature is already  measuring and version/ID should be useful also for production firmware?

**Comment by pmalessa** [comment]
Yes, this is possible

**Comment by pmalessa** [comment]
Once the latest issues are merged into master, please create a CalFW branch and remove listed features
