### ISSUE TITLE
CalFW: Measure and send Result via SPI

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#76]
- the rPi sends the requested measurement mode (ADC 1-4, current/voltage, samplerate):
 - js<{"MeasMode" : 0/1 for current/voltage,
       "MeasChannel" : Bit combination of 4 bit to select a combination of ADC1-4,
	   "MeasRate": sample rate in Hz
	  }
 - the rPi sends a command to start Measurement with a fixed duration in ms:
 - js<{„MeasStart“ : t}
 - The SAM measures the selected channels and saves the measured values
 - SAM sends the results back via SPI (This has to be discussed, how to do that)
 
**Definition of Done**
- [ ] code for mentioned task is complete. examples & documentations are complete.

- [ ] build chains are tested

- [ ] corresponding branch is closed

- [ ] merging is done

**Comment by begodev** [comment]
SAM will send result as a file (binary array) via small communication protocol extension
