### ISSUE TITLE
Measure Temperature

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#77]
- Command from rPi: js>["Temp"]
 - SAM measures the internal Chip Temperature, maybe with filtering?
 - SAM responds with {"Temp": 23.4} Temperature in Degrees Celsius as Float

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by begodev** [comment]
Implemented in #9 atm
