### ISSUE TITLE
CalFW: ext. EEPROM R/W Test

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#79]
- rPi sends a start signal to the SAM: js>["EEPROMTest"]
 - SAM writes defined testdata to EEPROM and reads it back.
 - SAM responds: {"EEPROMTest": 0/1} if failed/successful
 - Data to write to the EEPROM can be arbitrary but fixed
 
**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by begodev** [comment]
merged with #80

**Comment by dmitigr** [comment]
Available in master since c160a1cddb068a2179491885ab8344d81cf09cff.
