### ISSUE TITLE
Implementing module for non-volatile flash

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#8]
The settings (of the button menu) have to be saved permanently in the flash, as permanently as the firmware. So in respect of a board restart they should be permanently saved, but when a new firmware is flashed, they can be deleted too. 

Definition of Done
- [x] task mentioned in issue is solved. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by begodev** [comment]
The code is generally finished but the SAM's fuses has to be set from OpenOCD to enable the Smart EEPROM

**Comment by LeilaPiri** [comment]
**Definition of Done**
- [x] task mentioned in issue is solved. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done
