### ISSUE TITLE
Get Info

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#81]
- rPi sends command js>{ "ARMID", "fwVersion"}
 - SAM responds with Hardware Chip ID and firmware Version

**Definition of Done**
- [x] code for mentioned task is complete. examples & documentations are complete.

- [x] build chains are tested

- [x] corresponding branch is closed

- [x] merging is done

**Comment by IngoKaiser** [comment]
@begodev implemented in fw? no need to implement in driver as method  - can be requested by implemented getSetting?! @iluxa

**Comment by begodev** [comment]
> @begodev implemented in fw? no need to implement in driver as method - can be requested by implemented getSetting?! @iluxa

Yes, it is in the firmware.  If no any double-checking by another guy is required   (since  I've already checked it). I think it can be merged...

**Comment by begodev** [comment]
should be accessible via getSettings ("js>...") from the driver. js> works from the terminal

**Comment by pmalessa** [comment]
code checked, okay for me

**Comment by IngoKaiser** [comment]
tested on 10.0.0.12:

```
# ./rPIspi 0
SPI-0 Master
type the commands:
->
ARMID>\n
84BCA7B7-53385333-34202020-FF06212C
```
