### ISSUE TITLE
Config file config_osx for OSX cross-platform build is not available

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe#91]
It's been lost somewhere in https://github.com/panda-official/TimeSwipe/commit/826cd137c810a7ebe54d0f9b87f5d215faf1f178

[config_osx.gz](https://github.com/panda-official/TimeSwipe/files/4486779/config_osx.gz)

**Comment by thomaseichhorn** [comment]
Should now be fixed by https://github.com/panda-official/TimeSwipe/commit/a8c26a00e0e9857e088db409caede2b70c47f2ba . Could somebody verify please?

**Comment by dmitigr** [comment]
It's available in master.
