### ISSUE TITLE
Confusing value in firmware readme

### ISSUE THREAD

**Issue by IngoKaiser** [panda-official/TimeSwipe#92]
In https://github.com/panda-official/TimeSwipe/tree/master/

"You should see 48 outputs of ... not erased. This indicates a successful write process."

But test showed 54. please recheck and change if needed.

**Comment by thomaseichhorn** [comment]
The number actually depends on the size of the FW image being uploaded. At the time of writing, it was 48 :)
Will change to a generic text...

**Comment by thomaseichhorn** [comment]
Fixed by commit https://github.com/panda-official/TimeSwipe/commit/841bc8d62e234d7ec27a3931186389fa1f6b540d , closing
