### ISSUE TITLE
EEPROM Documentation

### ISSUE THREAD

**Issue by pmalessa** [panda-official/TimeSwipe#98]

**Comment by pmalessa** [comment]
Please write down a Documentation of our EEPROM Specification. I created a EEPROM_Doc branch and a doc/EEPROM Specification document for that.
Please copy important information from the official RPI HAT Specification to this document and list the current atom structure.
Please include a Calibration Status Atom, which is just a boolean which signals if the Calibration Data is valid.

**Comment by pmalessa** [comment]
Waiting for input of our hardware engineer about the calibration data structure

**Comment by pmalessa** [comment]
The Calibration data structure is now defined. Review pending

**Comment by dmitigr** [comment]
Available in master since c160a1cddb068a2179491885ab8344d81cf09cff.
